### ISSUE TITLE
Extension should create internal JDT Java projects for all dependant projects of current project

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#104]
@guw I've just noticed the following:

After a _Clean Java Language Server Workspace_ for #102 if I FIRST open a `*.java` of some "module" (Bazel target) which depends on another one (in the same `WORKSPACE`), then it will have some red - because the "dependant" project isn't created in JDT yet - the _Java Projects_ view initially only shows that single first module.

Of course, AFTER opening any `*.java` file of a "dependant" project the red in the "depending" project goes away. But, in an ideal world, it would be nice if "it did this by itself" and just immediately initialised all projects?

Or is that what it's already supposed to do? Then that doesn't work, and if there is any problem it gives up too early?

An example of this is in https://github.com/enola-dev/enola, when I openend e.g. `common/thing/src/main/java/dev/enola/thing/MessageToThingConverter.java` FIRST, then that `implements Converter` was red - until I opened `common/common/src/main/java/dev/enola/common/convert/Converter.java`

Note that I'm having another problem with dependencies from external Maven JAR libraries, see #103. I assumed that was an unrelated issue - unless it's the root cause of this?

PS: https://github.com/enola-dev/enola/issues/431 couldn't be the root cause of this, could it? There is no error in the `.log` about it...

**Comment by guw** [comment]
@vorburger After a clean you have to wait for the synchronization & Eclipse build to finish. Then everything should be ok. I don't know if this might be a problem of JDTLS not refreshing things properly in VS Code?

**Comment by vorburger** [comment]
@guw I've rechecked this on another (faster... dunno if related) computer now.

On that one, I do see _Java Projects_ populated "completely" (from all Bazel targets) after a _Clean Java Language Server Workspace_ and when opening e.g. `common/thing/src/main/java/dev/enola/thing/MessageToThingConverter.java` - no red.

> Note that I'm having another problem with dependencies from external Maven JAR libraries, see https://github.com/salesforce/bazel-vscode-java/issues/103. I assumed that was an unrelated issue - unless it's the root cause of this?

It may well be? Let me close this one, and let's get to the bottom of #103, first... if I still see this after that's solved, I'll re-open this one.
