### ISSUE TITLE
Mixing Maven-style and Bazel-style layout in a workspace: Possible, or a really dumb idea?

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#113]
I'm pondering and exploring switching the directory of my https://github.com/enola-dev/enola from a "Maven-style" (e.g. `core/impl/src/main/java/dev/enola/core`) to a fully "Bazel-style" (e.g. `java/dev/enola/model/xsd/Datatypes.java` etc.) layout in [this PR](https://github.com/enola-dev/enola/pull/637), starting small [here](https://github.com/enola-dev/enola/commit/81a33ccb5cc872c6d25f26806b0d86e4f30c3019). This will lead to "nested" `BUILD` files (e.g. `java/dev/enola/BUILD` and `java/dev/enola/model/BUILD`).

I suspect that with my existing [`.bazelproject`](https://github.com/enola-dev/enola/blob/e3e21004b96e61fc0e75f1097418aff8c8d1d4b4/.bazelproject#L1) as-is, this probably won't quite work? 

Wondering if I can I "mix & match" and gradually transition, or need to do one single big refactoring moving lots of stuff around?

@guw any input?

**Comment by guw** [comment]
Corrct. We don't support mixing.
