### ISSUE TITLE
Plugin does not work with Bazel 5

### ISSUE THREAD

**Issue by camearle20** [salesforce/bazel-vscode-java#20]
When trying to open a project with Bazel 5.1.0 installed, the plugin fails to generate a working JDT.LS configuration.  The log is attached.

[client.log.2022-03-25.txt](https://github.com/salesforce/bazel-vscode/files/8354197/client.log.2022-03-25.txt)

I made sure to clean the java language server workspace before trying to open a java source file, and the issue still occurs.  Is this a quick fix or something more involved?

**Comment by guw** [comment]
This might be fixed with https://github.com/salesforce/bazel-eclipse/commit/4569d6b617dedecd47473ab64a02116f03dff93f

**Comment by guw** [comment]
@plaird FYI. I think we should publish the Language Server and the Bazel Eclipse plug-in always at the same time. Once it's released I can look into building a new version of the VS Code extension.

**Comment by camearle20** [comment]
Just as a quick test I rebuilt the plugin from source and it looks like that took care of the issue, so it does seem like the commit you referenced fixed this.  Since the extension isn't in the VSCode marketplace yet anyway just using the version I built manually is completely fine for our team.

**Comment by plaird** [comment]
@guw we have [this Issue](https://github.com/salesforce/bazel-eclipse/issues/350) to think about how connected the product releases are. I think they at least need independent version numbers (e.g. if I refactor the Eclipse Import UI in BEF, that is a minor x.X.x BEF release and a patch x.x.X BJLS release).

**Comment by guw** [comment]
This works now
