### ISSUE TITLE
Rename project & repo from "bazel-vscode" to (something like) "bazel-vscode-java"

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#24]
Perhaps what this project & repo really are would be clearer if you considered renaming it from "bazel-vscode" to (something like) "bazel-vscode-java"?

GitHub's automated redirects are pretty good, so I wouldn't worry too much about breaking existing links. (It even works both for HTTP and for `git clone` with the git protocol as far as I remember.)

@guw

**Comment by vorburger** [comment]
https://github.com/salesforce/bazel-vscode VS https://github.com/bazelbuild/vscode-bazel, which have nothing to do with each other, can be confusing when one discovers this space. I get what's what now, but initially the current naming is confusing.

**Comment by guw** [comment]
done
