### ISSUE TITLE
Prettier Configuration File for uniform js formatting

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#26]
I want to propose some changes to the `gulpfile.js` for #23 but by VSC considerable reformats that file every time I touch it.

This is because I have the [Prettier Code Formatter VSC Extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) installed.

Would this project's maintainers welcome a PR which contribs an appropriate [Prettier Configuration File](https://prettier.io/docs/en/configuration.html) to settle on a uniform JS format for this project?

@guw

**Comment by guw** [comment]
Absolutely!
