### ISSUE TITLE
How to use / activate?

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#31]
I'm trying to get my head around how to use (activate?) this... 😈 

After not seeing #30 anymore, and having discovered the _Import Bazel Project_ command ([from here](https://github.com/salesforce/bazel-vscode/blob/7bbee72d85a8773816d7946a76c7e74ebc36d0e4/package.json)),

I am setting the _Project WORKSPACE location_ in that _Import wizard,_ clicking Load modules, checking a module, and clicking _Start import._

The VSC Window reloads, but... the imports still can't be resolved.

The _Classpath Configuration_ (from `redhat.java`) is still empty.

**Comment by vorburger** [comment]
```
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[Error - 10:42:34 PM] Feb 18, 2023, 10:42:34 PM Error occured while building workspace. Details: 
 message: The import io cannot be resolved; code: 268435846; resource: .../Bek.java; line: 3
 message: The import io cannot be resolved; code: 268435846; resource: .../Bek.java; line: 4
 message: ApiClient cannot be resolved to a type; code: 16777218; resource: .../Bek.java; line: 10
 message: Config cannot be resolved; code: 570425394; resource: .../Bek.java; line: 10
```

**Comment by vorburger** [comment]
The preferences mention a `bef.log` but I don't see one in my `$HOME`.

**Comment by vorburger** [comment]
FYI if I import the same project into Eclipse using `bazel-eclipse` instead of VSC with this project, I'm hitting https://github.com/salesforce/issues/450.

I'm not sure that's the cause of this. It "feels" like this is not even trying to import. Or it fails too silently, without providing details such as those.

**Comment by juskek** [comment]
This might not be an ideal fix, but since this extension was not working for me either I've managed to resolve my imports by creating the file `./workspace.code-workspace` and adding the following lines : 

```
{
    ...
    "settings": {
        ...
        "java.project.referencedLibraries": [
            "bazel-project_name/external/maven/**/*.jar",
        ],
    }
}
```

**Comment by guw** [comment]
see #35
