### ISSUE TITLE
Problems getting started

### ISSUE THREAD

**Issue by peakschris** [salesforce/bazel-vscode-java#35]
I'm facing a few issues getting started with a hello world project and VSCode Java. The main one is the my imports are not recognized:

![image](https://user-images.githubusercontent.com/77508021/232223939-2df48042-8543-4d1a-a88d-4b0c18b56aba.png)

![image](https://user-images.githubusercontent.com/77508021/232223958-f50e2475-93c5-474d-820d-567ca146131d.png)

This is despite listing the package in BUILD.bazel (java_binary rule):

![image](https://user-images.githubusercontent.com/77508021/232223989-a50d3185-c3a5-4280-8a1b-5e94f72458d0.png)

I'm using maven_install to pull in the dependencies, and have tried both in pinned and unpinned modes.

This is a great idea and we have very similar needs to yourselves in our migration to bazel whilst maintaining good IDE support.

Thanks! Chris

**Comment by juskek** [comment]
This might not be an ideal fix, but since this extension was not working for me either I've managed to resolve my imports by creating the file `./workspace.code-workspace` and adding the following lines : 

```
{
    ...
    "settings": {
        ...
        "java.project.referencedLibraries": [
            "bazel-project_name/external/maven/**/*.jar",
        ],
    }
}
```

**Comment by guw** [comment]
@peakschris @juskek The Bazel language server has undergone excessive rework. The extension is now available as preview release in the VS Code marketplace. Any interest in giving this another try?
