### ISSUE TITLE
Don't add entries for visible projects in `.vscode/settings.json`

### ISSUE THREAD

**Issue by guw** [salesforce/bazel-vscode-java#65]
See https://github.com/enola-dev/enola/pull/285/files#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R77

```
    ".github": false,
    ".vscode": false,
```

Those entries shouldn't be added to the settings file.

**Comment by guw** [comment]
@lonhutt is it possible to remove the `false` entries from the exclusion list?

**Comment by Siddhant-K-code** [comment]
@guw I think, we can close this issue now. It's already removed from [`.vscode/settings.json` file](https://github.com/vorburger/enola/blob/main/.vscode/settings.json)
