### ISSUE TITLE
Dependencies with @maven//: no longer work (in my particular project)

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#73]
When I open https://github.com/enola-dev/enola/ with v1.23.112291230 ([released 12/29/2023](https://marketplace.visualstudio.com/items?itemName=sfdc.bazel-vscode-java)), and then open e.g. the [`common/common/src/main/java/dev/enola/common/io/resource/FileResource.java`](https://github.com/enola-dev/enola/blob/main/common/common/src/main/java/dev/enola/common/io/resource/FileResource.java), then imports of `java.*` (JDK) and other `dev.enola...` (same workspace) are OK, but any "external" dependencies are not found - in that file that's e.g. all of the Guava related imports. That project [uses](https://docs.enola.dev/dev/dependencies/) `rules_jvm_external` in a `MODULE.bazel` with a  `maven.install` to grab that Guava JAR. (The project builds fine on the CLI, of course.)

I'm pretty sure I used to have this working, but I cannot get it to work anymore on a new computer, so either it broke, quite possibly by some (Bazel?) or other upgrade I did over the last weeks - or I just cannot remember where all to click to kick it correctly? I [usually](https://docs.enola.dev/dev/ide/) right-click on  `common/common` and _Synchronize Projects with Bazel View_ and then _Refresh Classpath from Bazel BUILD file_ - but that doesn't seem to do the trick.

If it's not a bug and just a problem between the chair and the screen (i.e. me!), then at the very least I can contribute an initial version of a "troubleshooting" doc somewhere here. Or you could improve the automation so that it "just works out of the box".

@guw how do we best debug this?

**Comment by vorburger** [comment]
FYI I'm actually not yet very familiar with how exactly it integrates with VSC.

Where should I see the `guava*.jar` on a classpath of the `common/common` "module/project" in the UI? Or is there no UI?

Is it normal / expected that the _Referenced Libraries_ in the _Java Projects_ view is empty? Or should a `guava*.jar` appear there? (Even thought that's "global" for all of "enola" and not just for `common/common`?)

I've also just discovered and am reading up on https://code.visualstudio.com/docs/java/java-project#_lightweight-mode ... that sounds a bit like I may somehow be in that "lightweight" instead of VSC's "standard Java mode"? But the icon is a `{ }` which seems to indicate _"workspace opened with standard mode",_ so that's probably not it.

**Comment by vorburger** [comment]
> Is it normal / expected that the Referenced Libraries in the Java Projects view is empty?

BTW [After reading this](https://code.visualstudio.com/docs/java/java-project#_manage-dependencies-for-unmanaged-folder), I just learnt that because I already had the [Project Manager for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency) extension installed, I can manually add e.g. `bazel-bin/external/rules_jvm_external~5.3~maven~maven/com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar` there - but that's dumb, of course.

When I use [the _Configure Java Runtime_ command](https://code.visualstudio.com/docs/java/java-project#_configure-runtime-for-projects), it says that the _Type_ for `enola` is _Unmanaged folder._  Is that expected? Or should that say _"Bazel",_ just like it otherwise says _Maven_ or _Gradle?_

PS: I don't suppose in VSC there can be "conflicts" between different Java plugins? [I also have all of these other plugins installed](https://github.com/vorburger/vorburger-dotfiles-bin-etc/blob/main/dotfiles/code/extensions.txt)... Should I be "force excluding" any of them in [`enola/.vscode/extensions.json`](https://github.com/enola-dev/enola/blob/main/.vscode/extensions.json)?

**Comment by guw** [comment]
This looks like a  regression.

I cannot currently build it, though. What do I need to install on MacOS?
```
ERROR: An error occurred during the fetch of repository 'rules_go~0.44.1~go_sdk~main___host_0':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_gwagenknecht/53e507aad399b2eeb9515f5f4f440319/external/rules_go~0.44.1/go/private/sdk.bzl", line 23, column 30, in _go_host_sdk_impl
		goroot = _detect_host_sdk(ctx)
	File "/private/var/tmp/_bazel_gwagenknecht/53e507aad399b2eeb9515f5f4f440319/external/rules_go~0.44.1/go/private/sdk.bzl", line 538, column 13, in _detect_host_sdk
		fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: <builtin>: fetching go_host_sdk_rule rule //:rules_go~0.44.1~go_sdk~main___host_0: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_gwagenknecht/53e507aad399b2eeb9515f5f4f440319/external/rules_go~0.44.1/go/private/sdk.bzl", line 23, column 30, in _go_host_sdk_impl
		goroot = _detect_host_sdk(ctx)
	File "/private/var/tmp/_bazel_gwagenknecht/53e507aad399b2eeb9515f5f4f440319/external/rules_go~0.44.1/go/private/sdk.bzl", line 538, column 13, in _detect_host_sdk
		fail("Could not detect host go version")
Error in fail: Could not detect host go version
```

**Comment by guw** [comment]
@vorburger The projects imports without errors in Eclipse. Thus, the plug-in is fine.

However, I noticed a problem in VS Code. I had an old workspace and this one fails. The Problems view in VS Code shows:
> The container 'Persisted container [com.salesforce.bazel.eclipse.BAZEL_CONTAINER for project [common.common]]' references non existing library `'.../external/rules_jvm_external~5.3~maven~maven/com/google/guava/guava/32.1.2-jre/processed_guava-32.1.2-jre.jar'`

Looking carefully, it points to the **old** Guava version. This leads me to think that maybe Sync isn't working correctly. The _"Java: Open All Log Files"_ command is helpful. The `.log` file shows:
```
!ENTRY com.salesforce.bazel.eclipse.core 4 0 2024-01-05 07:22:56.354
!MESSAGE Unable to sync workspace '/.../oss/enola' because the project is not accessible!
```

That is weird. Perhaps something in the internal VS Code state is off?

There is a **reset** command you can use (Cmd+Shift+P): _"Java: Clean Java Lanaguage Server Workspace"_. After executing this command everything works again in VS Code.

**Comment by vorburger** [comment]
>  I can contribute an initial version of a "troubleshooting" doc somewhere here

#76

> The container 'Persisted container [com.salesforce.bazel.eclipse.BAZEL_CONTAINER for project [common.common]]' references non existing library '.../external/rules_jvm_external~5.3~maven~maven/com/google/guava/guava/32.1.2-jre/processed_guava-32.1.2-jre.jar'

> !ENTRY com.salesforce.bazel.eclipse.core 4 0 2024-01-05 07:22:56.354
> !MESSAGE Unable to sync workspace '/.../oss/enola' because the project is not accessible!

I don't see those 2 errors you have; maybe its Mac vs Linux specific, or, more likely, don't even get that far and fail before... see attached [log.txt](https://github.com/salesforce/bazel-vscode-java/files/13841085/log.txt) and [client.log.2024-01-05.json](https://github.com/salesforce/bazel-vscode-java/files/13841064/client.log.2024-01-05.json) - don't these look pretty suspicious, or do you think this is just normal, I seem to have many many of these (see attached):

```
!ENTRY org.eclipse.core.jobs 4 2 2024-01-05 11:37:47.645
!MESSAGE An internal error occurred during: "Classpath Update Job".
!STACK 0
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.preferences.Preferences.getAnnotationType(Preferences.java:2375)
	at org.eclipse.jdt.ls.core.internal.preferences.Preferences.updateAnnotationNullAnalysisOptions(Preferences.java:2326)
	at org.eclipse.jdt.ls.core.internal.handlers.ClasspathUpdateHandler$1.runInWorkspace(ClasspathUpdateHandler.java:66)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2024-01-05 11:37:48.438
!MESSAGE An internal error occurred during: "Classpath Update Job".
!STACK 0
java.lang.IllegalArgumentException: Attempted to endRule: null, does not match most recent begin: R/.  See log for trace information if rule tracing is enabled.
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:68)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPop(ThreadJob.java:126)
	at org.eclipse.core.internal.jobs.ThreadJob.pop(ThreadJob.java:391)
	at org.eclipse.core.internal.jobs.ImplicitJobs.end(ImplicitJobs.java:118)
	at org.eclipse.core.internal.jobs.JobManager.endRule(JobManager.java:793)
	at org.eclipse.core.internal.resources.WorkManager.checkOut(WorkManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1598)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:50)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 1 2024-01-05 11:37:48.439
!MESSAGE Worker thread ended job: Classpath Update Job(1313), but still holds rule: ThreadJob(Classpath Update Job(1313),[R/])
!STACK 0
java.lang.IllegalStateException: Worker thread ended job: Classpath Update Job(1313), but still holds rule: ThreadJob(Classpath Update Job(1313),[R/])
	at org.eclipse.core.internal.jobs.ImplicitJobs.endJob(ImplicitJobs.java:139)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:83)
```

There is also this, which I'll try next if I can reproduce it on #74:

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2024-01-05 11:37:51.457
!MESSAGE Error occured while building workspace. Details: 
 message: Preview features enabled at an invalid source release level 11, preview can be enabled only at source level 21; code: 2098258; resource: /home/vorburger/git/github.com/enola-dev/enola/cli/src/main/java/dev/enola/cli/CLI.java;
```
