### ISSUE TITLE
Build tool conflicts are detected in workspace. Which one would you like to use?

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#82]
When I use this extension for https://github.com/enola-dev/enola/, there is always / sometimes (?) a pop-up, from RHT Java, asking:

Build tool conflicts are detected in workspace. Which one would you like to use? _Maven_ -or- _Gradle_

This seems to be reproducible (for me) with:

* redhat.java v1.27.2024011308
* sfdc.bazel-vscode-java v1.24.101141409
* vscjava.vscode-gradle v3.13.5  - BUT I have it _disabled in Workspace_
* vscjava.vscode-maven v0.43.0 - BUT I have it _disabled in Workspace_

Interestingly, just clicking _Maven_ seems to do the trick - and actually correctly initializes the Bazel Java support (for me).

I'm not sure if there would be a way for this extension to hook into VSC in some way to avoid this confusion?

Otherwise, perhaps just adding this to the [Troubleshooting Guide](https://github.com/salesforce/bazel-vscode-java/blob/main/docs/troubleshoot.md) is useful - at least until this is "fixed" (if it even can be).

@guw any thoughts?

**Comment by guw** [comment]
I think this is a feature request for the RedHat Extension.
https://github.com/redhat-developer/vscode-java/blob/56f2cfb3fca762170595dbef08534be2f6063f9e/src/utils.ts#L173

**Comment by vorburger** [comment]
> Note, as a workaround you can disable Maven & Grade support in workspace settings @vorburger.

Ah! That sounds like something to try, and perhaps document here in the Troubleshooting. 

I couldn't immediately find the setting ID - do you happen to know it, or even have an example to point to?

**Comment by guw** [comment]
`java.import.gradle.enabled = false` && `java.import.maven.enabled = false`
