### ISSUE TITLE
Go To Type Definition opens .class instead of .java

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#93]
In https://github.com/enola-dev/enola/, when I _Go To Type Definition_ e.g. in some `**/src/test/java/**/*.java` editor on a "symbol" that is something in the `src/main` (instead of `/test`) of the same module/project/whatever, then instead of .java it opens some read-only .class (read-only, but not decompiled; it's the correct source text).

I'm not sure how to describe this more accurately - let me know if some... screenshots (?), or something, would help to clarify.

@guw

**Comment by vorburger** [comment]
Hm, this strangely only seems to happen in some cases, and I haven't found out the correlation why, yet:

For example, when `common/common/src/test/java/dev/enola/common/io/resource/ClasspathUrlResourceTest.java` is open and I `F12` on that `UrlResource` in line 44, then it correctly opens `common/common/src/main/java/dev/enola/common/io/resource/UrlResource.java`.

However when I'm in `core/impl/src/test/java/dev/enola/core/meta/TypeRepositoryTest.java` (which is not yet on the `main` branch as of writing this, but will eventually be merged in, from https://github.com/enola-dev/enola/pull/451) and Ctrl-Click on the `TypeRepositoryBuilder`, then instead of `core/impl/src/main/java/dev/enola/core/type/TypeRepositoryBuilder.java`, it opens a `TypeRepositoryBuilder.class` from somewhere... check out this screenshot:

![Screenshot from 2024-02-09 15-33-55](https://github.com/salesforce/bazel-vscode-java/assets/298598/69b97e88-32a6-4205-bf18-67a9e45efecc)

so apparently, in some cases, it doesn't set up the Inter-Project Dependency in the underlying JDT correctly?

Looks like for the this ^^^ case it references this `libimpl-ijar.jar`, whereas in the case where it works it "does the right thing", and jumps into the project, instead of opening a `class` from (in that case) `libcommon-ijar.jar`.

The `BUILD` for those 2 modules look very similar though... it's a `[java_test(` with a "simple" `deps = [":common",` respectively `deps = [ ":impl",`. 

Strange.

**Comment by vorburger** [comment]
What makes this more annoying than simply Navigating is that when one makes changes (like adds new methods, or whatever) to code under test in `main/java` code, they are not "visible" (red) in `test/java`, until a full rebuild - that's quite a PITA.

**Comment by guw** [comment]
@vorburger I tried to reproduce but I ran into an issue:
```
ERROR: .../enola/tools/hello/BUILD:29:13: Compiling Java headers tools/hello/libhello_lib-hjar.jar (1 source file) failed: (Exit 1): java failed: error executing Turbine command (from target //tools/hello:hello_lib) external/local_jdk/bin/java '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 47 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
tools/hello/src/main/java/dev/enola/common/hello/Library.java:27: error: unexpected input: {
        return STR."hello, \{planet}";
                            ^
```

**Comment by vorburger** [comment]
> @vorburger I tried to reproduce but I ran into an issue:

See https://github.com/enola-dev/enola/pull/452, but...

... even if you are on a commit from before that fix, you should never see this.

Could this be due to some Bazel/ Bazelisk version discrepancy between us? E.g. related to #88?

Having said that... I (now) can no longer reproduce this problem myself - huh?!

Unless you are interested in digging more, let's close this? I'll comment when (if) I see it again, hopefully then with a clear(er) reproducer.

**Comment by guw** [comment]
Going to the `.class` usually happens when the `.java` source is not properly set up as project. It can also happen if there is a bug in classpath resolution and Bazel Eclipse fails to resolve a `jar` dependency to an Eclipse project. Please re-open when you have such a case.
