### ISSUE TITLE
How to disable JDT _"Discouraged access"_ warnings?

### ISSUE THREAD

**Issue by vorburger** [salesforce/bazel-vscode-java#99]
I'm adding a new Maven library (https://rdf4j.org) to https://github.com/enola-dev/enola, and VSC is showing warnings like:

Discouraged access: The type 'IRI' is not API (restriction on required library '/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/execroot/_main/bazel-out/k8-fastbuild/bin/external/maven/org/eclipse/rdf4j/rdf4j-model-api/5.0.0-M2/processed_rdf4j-model-api-5.0.0-M2.jar')

for **_every_** type I'm using anywhere for that library... which isn't strictly blocking - but fairly "ugly" (to my eyes, at least).

How do we configure Eclipse JDT settings with this extension, to set this particular warning to ignore everywhere? (Like one used to be able to do in Eclipse, somewhere.)

Researching this a bit, I've stumbled upon e.g. https://stackoverflow.com/a/54504776/421602 - could there be an equivalent in `settings.json`?

Or is there some way to configure JDT "Workspace Preferences" for `vscode-java` "globally" from `settings.json`?

@guw

**Comment by guw** [comment]
Where are you using the API? The error message is expected if there is a missing *direct* dependency in `BUILD.bazel` target definition.

**Comment by vorburger** [comment]
> Where are you using the API? The error message is expected if there is a missing _direct_ dependency in `BUILD.bazel` target definition.

Oh, I see! Yeah, it disappeared now - of course; sorry for the noise!
